
name: "Issue/PR Tag"
on:
  workflow_call:
    inputs:
      org_name:
        required: true
        type: string
      tag_team:
        required: true
        type: string
      issue: 
        required: false
        type: string
      pr: 
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  notify:
    if: ${{ github.repository_owner == inputs.org_name }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: devops-actions/issue-comment-tag@ec5e2b8d5f031330ff19bf4ee5b5252b1176995a # v0.1.8
        with:
          team: ${{ inputs.tag_team }}
          issue: ${{ input.issue }}
          pr: ${{ input.pr }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.token }}
